### ISSUE TITLE
Problems while configuring stackit_kubernetes_cluster

### ISSUE THREAD

**Issue by Sherlocked97** [SchwarzIT/terraform-provider-stackit#101]
Dear Sir or Madam,

Right now we´re working on the setup of our kuberentes node-pool and want to add a minimum of 1 node and a maximum of ~30 nodes, while keeping the max_surge at 1.
Unfortunately we always get the same error after increasing the maximum amount above 10.

Our code looks like this:
```
minimum = 1
maximum = 30 
max_surge = 1
```
and the error code we get is the following:

> Error: Failed cluster validation
> with stackit_kubernetes_cluster.qs-splunk,
> on k8s_cluster_setup.tf line 7, in resource "stackit_kubernetes_cluster" "qs-splunk":
> 7: resource "stackit_kubernetes_cluster" "qs-splunk" {
> max surge value must be in the range of 1..10

Thanks for the help.

**Comment by do87** [comment]
Fixed client bug as part of https://github.com/SchwarzIT/community-stackit-go-client/pull/121
