### ISSUE TITLE
Stackit SKE Creating not working for me

### ISSUE THREAD

**Issue by philipphomberger** [SchwarzIT/terraform-provider-stackit#137]
I have already try to change the URL using the ENV var. So the Url looks now correct for me. 

![grafik](https://github.com/SchwarzIT/terraform-provider-stackit/assets/13222043/8cf72d40-a060-44e3-8e66-a2113b0721d7)

Befor change url to api.stackit.cloud I have the same error message with the Url too.
 https://ske.api.eu01.stackit.cloud/v1/projects/ba77d738-8691-4340-948f-29da96955545/clusters/groot-dev

Working some weeks ago fine.
I have already update my Provider to 1.18.1. 

Thank you for your advice.

**Comment by do87** [comment]
can you provide your terraform configuration?

**Comment by do87** [comment]
our acceptance tests succeed without a problem and unfortunately there's no further information from the reporter. i'm closing the issue.
