### ISSUE TITLE
Rabbit-MQ is not shown in portal after creation

### ISSUE THREAD

**Issue by fellnase** [SchwarzIT/terraform-provider-stackit#140]
After creating a rabbit-mq service with terraform, it won't be shown in the Portal under the servce tab of the Projekt.

resource "stackit_rabbitmq_instance" "rabbitmq-dev-instance" {
  name       = "rabbitmq-dev"
  project_id = "XXXXXX-XXXX-XXXX-XXXX-12345678a"
  version    = "3.7"
  plan       = "stackit-rabbitmq-single-small"  
}

resource "stackit_rabbitmq_credential" rabbitmq-dev-instance_credetials" {
  project_id  = "XXXXXX-XXXX-XXXX-XXXX-12345678a"
  instance_id = stackit_rabbitmq_instance.rabbitmq-dev-instance.id  
}

stackit_rabbitmq_instance.rabbitmq-dev-instance: Still creating... [6m20s elapsed]
stackit_rabbitmq_instance.rabbitmq-dev-instance: Creation complete after 6m21s [id=XXXXX-XXXX-XXXX....]
stackit_rabbitmq_credential.rabbitmq-dev-instance_credetials: Creating...
stackit_rabbitmq_credential.rabbitmq-dev-instance_credetials: Still creating... [10s elapsed]
stackit_rabbitmq_credential.rabbitmq-dev-instance_credetials: Creation complete after 18s [id=XXXXX-XXXX-XXXX....]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

**Comment by do87** [comment]
Hi @fellnase 
that's not an issue with the provider. your instance was in fact created but it's not yet visible in the portal because the portal team is still working on integrating the public APIs.
