### ISSUE TITLE
Issues with Stackit Kubernetes Kube File

### ISSUE THREAD

**Issue by Henning1919** [SchwarzIT/terraform-provider-stackit#143]
Hello,

we are trying to deploy our SKE Cluster with help from 

[Docs overview | hashicorp/kubernetes | Terraform Registry](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs)

For the creation of the Cluster wer are using https://registry.terraform.io/providers/SchwarzIT/stackit/latest/docs/resources/kubernetes_cluster

Can you please add following attributes to the Provider - so that we do not need to use the Kube Config File? 

[1f50d537-79a5-4a27-95aa-f2e9b2963610](https://github.com/SchwarzIT/terraform-provider-stackit/assets/80468998/bd414949-ae7a-4fb7-bd81-a565a4815869)

**Comment by do87** [comment]
At the time of writing this, STACKIT's API only provides kubeconfig

https://internal-docs.api.eu01.stackit.cloud/documentation/ske#tag/Credentials/operation/SkeService_GetClusterCredentials
