### ISSUE TITLE
Add ACL IP Adresse in Postgres Flex where could we find the right IP Adresse Range in new created SKE Cluster

### ISSUE THREAD

**Issue by Henning1919** [SchwarzIT/terraform-provider-stackit#144]
Hello,

we want to create a Stackit SKE Cluster which uses Stackit Flex Postgres DB.

When creating the SKE Cluster - the SKE Network Router is beeing automatically created - but the IP Adresses do not always match with the Postgres Flex ACL. 

Can you add a feature to read out the SKE IP Range - so that it can be set for the Postgres Flex Instance.

Regards
Henning

**Comment by do87** [comment]
There's currently no way of knowing the IP address of the service
However, the current ranges are known for STACKIT:
```
    "193.148.160.0/19",
    "45.129.40.0/21",
    "45.135.244.0/22"
```
