### ISSUE TITLE
Acceptance tests DSA service plans

### ISSUE THREAD

**Issue by dsa-github** [SchwarzIT/terraform-provider-stackit#152]
Hi, since a few weeks we have implemented new service plans for our DSA services, the old one will become obsolete and are more or less deprecated. 
Can you please check that there no old service plans using so that we can delete them?

New service plans schema:
stackit-logme-16.64.5000-replica
(Servicename-CPU-RAM-DISK-cluster(yes/no))

Old service plans schema:
stackit-logme-cluster-medium-non-ssl

Newer products like OpenSearch, MariaDB10.6 or LogMe2 have already only the new plans.

Thanks & BR
Daniel Frincu

**Comment by do87** [comment]
Hey @dsa-github 
All DSA default service plans have been updated.
