### ISSUE TITLE
Argus Grafana not visible 

### ISSUE THREAD

**Issue by Henning1919** [SchwarzIT/terraform-provider-stackit#182]
Hello,

we have created with Terraform the Argus Instance - everything worked only the Grafana itself is not visible:

"argus_id": "78762e85-ab0b-4c21-b3c1-c2cea46adcdc",
  "argus_pass": "****,
  "argus_user": "stackit7_78762e85-ab0b-4c21-b3c1-c2cea46adcdc_57fbcb35-2bee-4ba0-9e96-c4dff39ffc27",
  "grafana_pw": "****",
  "grafana_url": "[https://ui.stackit7.argus.eu01.stackit.cloud/instances/78762e85-ab0b-4c21-b3c1-c2cea46adcdc",](https://ui.stackit7.argus.eu01.stackit.cloud/instances/78762e85-ab0b-4c21-b3c1-c2cea46adcdc%22,)
  "grafana_user": "admin",
  "metrics_url": "[https://storage.api.stackit7.argus.eu01.stackit.cloud/instances/78762e85-ab0b-4c21-b3c1-c2cea46adcdc"](https://storage.api.stackit7.argus.eu01.stackit.cloud/instances/78762e85-ab0b-4c21-b3c1-c2cea46adcdc%22)

We have enabled the public access is enabled - but it seems not to work as intended.

Thank you
Regards
Henning

**Comment by do87** [comment]
from the user: Argus 7 Instance has an issue, newer version fixes this problem
