### ISSUE TITLE
Terraform created instances are not visible in web interface

### ISSUE THREAD

**Issue by JonathanDeul** [SchwarzIT/terraform-provider-stackit#197]
Hi,
if I create instances via terraform, they are not displayed in the services tab of the stackit web GUI.
This is problematic because the first sign that there is still an (expensive) instance running is the invoice coming about 2 days later. (And at this point the instance(s) may already be running for 3 days straight)
I am not sure if the problem originates from the terraform provider or is an issue within stackit.

**Comment by do87** [comment]
Hey, this is only a visual 'bug' because the APIs are not yet fully integrated into the STACKIT portal.
Not really a provider issue
