### ISSUE TITLE
Invalid return value for `stackit_postgres_credential.username`

### ISSUE THREAD

**Issue by JorTurFer** [SchwarzIT/terraform-provider-stackit#97]
Hello,
I'm using `stackit_postgres_credential` and trying to get the connection data but it looks that `username` return the `database_name` instead of the `username`.

![image](https://user-images.githubusercontent.com/36899226/214563164-6d232169-7f4f-4fc3-9bef-06946ec6a125.png)

Having access to both values would be nice as the db name is something internal unrelated with the server name

**Comment by do87** [comment]
thanks for your report, I'll look into it

**Comment by do87** [comment]
the provider is using `Name` as the username
https://github.com/SchwarzIT/terraform-provider-stackit/blob/main/stackit/internal/resources/data-services/credential/helpers.go#L23

I'll raise a question to DSA team if that's correct or not, as the client (generated from their swagger spec) doesn't provide a `Username` field

**Comment by do87** [comment]
bug should be fixed in v1.11.8 @JorTurFer

**Comment by JorTurFer** [comment]
Thanks!
We are using `uri` because our app also support that format, I won't be able to test the fix, but thanks anyway :)
